name: Deploy Crypto App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crypto-dashboard
    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      
      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: '25.2.1'

      - name: Install dependencies
        run: yarn install

      - name: Set environment variables
        run: 
          echo "COINBASE_PRIVATE_KEY=${{ secrets.COINBASE_PRIVATE_KEY }}" >> .env
          echo "COINBASE_KEY_NAME=${{ secrets.COINBASE_KEY_NAME }}" >> .env
          echo "VITE_COINGECKO_API_KEY_FREE=${{ secrets.VITE_COINGECKO_API_KEY_FREE }}" >> .env
        # Add more env vars if needed
        # run: echo "VITE_OTHER_SECRET=${{ secrets.OTHER_SECRET }}" >> .env

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          personal_token: ${{ secrets.ACTIONS_KEY }}
          publish_dir: ./dist
